"""Turn the result CSVs into tables (docs/RESULTS_TABLES.md) and figures (results/figures/*.png).

Every number in docs/RESULTS.md comes from the tables this script writes.
Confidence intervals: 95 % bootstrap over conversations (paired where systems are compared).

    python scripts/make_report.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

PROJECT = Path(__file__).resolve().parents[1]
RES = PROJECT / "results"
FIG = RES / "figures"
OUT_MD = PROJECT / "docs" / "RESULTS_TABLES.md"

# Categorical slots in fixed order (validated palette): blue, orange, aqua; grey for references.
BLUE, ORANGE, AQUA, GREY = "#2a78d6", "#eb6834", "#1baf7a", "#a3a29d"
INK, INK2 = "#0b0b0b", "#52514e"
plt.rcParams.update({
    "figure.dpi": 110, "savefig.dpi": 220, "font.size": 10, "axes.titlesize": 11, "axes.titleweight": "bold",
    "axes.spines.top": False, "axes.spines.right": False, "axes.edgecolor": "#c9c8c3", "axes.linewidth": 0.8,
    "axes.grid": True, "grid.color": "#ebeae6", "grid.linewidth": 0.8, "axes.axisbelow": True,
    "axes.labelcolor": INK2, "xtick.color": INK2, "ytick.color": INK2, "text.color": INK,
    "legend.frameon": False, "font.family": "DejaVu Sans",
})

OVL = ["ovl-none", "ovl-low", "ovl-high"]
OVL_LABEL = {"ovl-none": "no overlap", "ovl-low": "some overlap\n(~4 % of time)",
             "ovl-high": "heavy overlap\n(~12 % of time)"}
NOISE = ["clean", "village10", "market5"]
NOISE_LABEL = {"clean": "clean", "village10": "village, 10 dB", "market5": "market, 5 dB"}


def boot_ci(values: np.ndarray, weights: np.ndarray | None = None, n: int = 2000, seed: int = 0) -> tuple[float, float]:
    """95 % bootstrap CI of a (weighted) mean over conversations."""
    rng = np.random.default_rng(seed)
    values = np.asarray(values, float)
    w = np.ones_like(values) if weights is None else np.asarray(weights, float)
    idx = rng.integers(0, len(values), size=(n, len(values)))
    stats = (values[idx] * w[idx]).sum(1) / w[idx].sum(1)
    return float(np.percentile(stats, 2.5)), float(np.percentile(stats, 97.5))


def paired_diff_ci(a: pd.Series, b: pd.Series, seed: int = 0) -> tuple[float, float, float]:
    """Mean of (a − b) over the same conversations, with a 95 % bootstrap CI."""
    d = (a - b).dropna().to_numpy()
    lo, hi = boot_ci(d, seed=seed)
    return float(d.mean()), lo, hi


def pct(x: float) -> str:
    return f"{100 * x:.1f} %"


def bar_group(ax, groups, series, values, errs, colors, labels, ylabel, fmt=pct):
    k = len(series)
    width = 0.8 / k
    x = np.arange(len(groups))
    for i, (s, col, lab) in enumerate(zip(series, colors, labels)):
        v = np.array([values[s][g] for g in groups])
        e = np.array([errs[s][g] for g in groups]).T if errs else None
        ax.bar(x + (i - (k - 1) / 2) * width, v, width * 0.92, color=col, label=lab, yerr=e,
               error_kw={"elinewidth": 1, "ecolor": INK2, "capsize": 2})
    ax.set_xticks(x, [OVL_LABEL.get(g, NOISE_LABEL.get(g, g)) for g in groups])
    ax.set_ylabel(ylabel)
    ax.yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(lambda y, _: f"{100 * y:.0f}%"))
    ax.grid(axis="x", visible=False)


def main(asr: str = "indicconformer") -> None:
    FIG.mkdir(parents=True, exist_ok=True)
    md: list[str] = ["# Results tables (generated by `scripts/make_report.py` — do not edit by hand)\n"]

    # ------------------------------------------------------------ Stage 1: separation
    for split in ("dev", "test"):
        f = RES / f"separation_{split}.csv"
        if not f.exists():
            continue
        sep = pd.read_csv(f)
        t = sep.groupby(["view", "model", "noise"]).si_sdri.mean().unstack("noise")[NOISE]
        t["all"] = sep.groupby(["view", "model"]).si_sdri.mean()
        t["n"] = sep.groupby(["view", "model"]).size()
        md += [f"## Stage 1 — separation, SI-SDR improvement in dB ({split} set)\n",
               t.round(2).reset_index().to_markdown(index=False), "",
               "`n` counts overlap regions (overlap-region rows) or whole 2-speaker recordings (whole-recording rows); "
               "0 dB = no better than the untouched mixture.\n"]
        if split == "test":
            # Like-for-like: the whole-recording view only exists for 2-speaker conversations with overlap, so
            # compare against the overlap regions of exactly those conversations, paired per conversation.
            ct = sep[sep.model == "convtasnet"]
            whole = ct[ct.view == "whole-recording"].set_index("id").si_sdri
            regions = ct[(ct.view == "overlap-region") & ct.id.isin(whole.index)].groupby("id").si_sdri.mean()
            m, lo, hi = paired_diff_ci(regions, whole)
            n_pair = int((regions - whole).notna().sum())
            wins = int(((regions - whole) > 0).sum())
            md += [f"**Matched comparison (Conv-TasNet, the same {n_pair} two-speaker conversations):** separating only the "
                   f"overlapping stretches beats separating the whole recording by **{m:+.2f} dB** "
                   f"(95 % CI {lo:+.2f} to {hi:+.2f}), and wins in {wins} of {n_pair} conversations.\n"]
            fig, ax = plt.subplots(figsize=(6.4, 3.2))
            g = sep[sep.model == "convtasnet"].groupby(["view", "noise"]).si_sdri
            vals = {v: g.mean()[v].to_dict() for v in ("overlap-region", "whole-recording")}
            errs = {v: {n: np.abs(np.array(boot_ci(sep[(sep.model == "convtasnet") & (sep.view == v) & (sep.noise == n)].si_sdri)) - vals[v][n])
                        for n in NOISE} for v in vals}
            bar_group(ax, NOISE, list(vals), vals, errs, [BLUE, ORANGE],
                      ["only the overlapping stretch (Order B)", "the whole recording (Order A)"], "SI-SDR improvement (dB)",
                      fmt=lambda x: f"{x:.1f}")
            ax.yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(lambda y, _: f"{y:.0f}"))
            ax.set_title("Stage 1 · Conv-TasNet helps far more on overlaps than on whole recordings", loc="left")
            ax.legend(loc="upper right")
            fig.tight_layout()
            fig.savefig(FIG / "stage1_separation.png", bbox_inches="tight")
            plt.close(fig)

    # ------------------------------------------------------------ Stage 2: diarization tuning (dev)
    tp = RES / "tuned_params.json"
    if tp.exists():
        tuned = json.loads(tp.read_text(encoding="utf-8"))
        rows = [{"system": k, **{kk: vv for kk, vv in v.items() if kk != "cluster_kwargs"}, **v["cluster_kwargs"]}
                for k, v in tuned.items()]
        md += ["## Stage 2 — diarizer settings chosen on the dev set\n", pd.DataFrame(rows).to_markdown(index=False), ""]

    # ------------------------------------------------------------ Stage 3: ASR choice
    ac = RES / "asr_comparison.json"
    if ac.exists():
        a = json.loads(ac.read_text(encoding="utf-8"))
        t = pd.DataFrame(a["table"])[["model", "set", "n", "hours", "wer", "cer", "english_word_recall", "rtf"]]
        md += ["## Stage 3 — ASR model comparison (single utterances, real speech)\n", t.round(4).to_markdown(index=False), "",
               f"Chosen on Vaani test: **{a['chosen_model']}**. Hinglish romaniser: "
               f"{a['romaniser_english_spelling_acc']:.1%} of {a['romaniser_pairs']} English words spoken inside Hindi "
               f"(Vaani test) come out in correct English spelling.\n"]

    # ------------------------------------------------------------ End-to-end (test)
    ev = RES / f"eval_test_{asr}.csv"
    if not ev.exists():
        OUT_MD.write_text("\n".join(md), encoding="utf-8")
        print("no end-to-end results yet; wrote partial tables")
        return
    df = pd.read_csv(ev)
    order = ["oracle-clean", "oracle-mix", "oracle-sep", "B-spectral", "B-gmm", "B-nosep", "B-pyannote", "A-spectral", "A-gmm"]
    rows = []
    for s in order:
        g = df[df.system == s]
        cp = g.cp_errors.sum() / g.ref_words.sum()
        lo, hi = boot_ci((g.cp_errors / g.ref_words).to_numpy(), g.ref_words.to_numpy())
        dlo, dhi = boot_ci(g.der.to_numpy())
        rows.append({"system": s, "cpWER": cp, "cpWER 95% CI": f"{pct(lo)} – {pct(hi)}", "cpCER": g.cpcer.mean(),
                     "DER": g.der.mean(), "DER 95% CI": f"{pct(dlo)} – {pct(dhi)}", "missed": g.missed.mean(),
                     "false alarm": g.false_alarm.mean(), "confusion": g.confusion.mean(), "JER": g.jer.mean(),
                     "|speaker-count error|": g.spk_count_err.abs().mean(), "turns separated": g.separated_frac.mean(),
                     "n": len(g)})
    main_t = pd.DataFrame(rows).set_index("system")
    fmt = main_t.copy()
    for c in ["cpWER", "cpCER", "DER", "missed", "false alarm", "confusion", "JER", "turns separated"]:
        fmt[c] = fmt[c].map(pct)
    fmt["|speaker-count error|"] = fmt["|speaker-count error|"].map(lambda x: f"{x:.2f}")
    n_conv = df.id.nunique()
    minutes = df.drop_duplicates("id").duration_s.sum() / 60 if "duration_s" in df else float("nan")
    md += [f"## End-to-end on the test set ({n_conv} conversations, {minutes:.0f} min)\n",
           "cpWER = words wrong **or attributed to the wrong speaker** (pooled over all words). DER with 0.25 s collar, "
           "overlap scored. Oracle rows use the true speaker timeline.\n", fmt.to_markdown(), ""]

    # by condition
    for metric, name in (("cpwer", "cpWER"), ("der", "DER")):
        for dim, levels in (("overlap_level", OVL), ("noise", NOISE)):
            if metric == "cpwer":
                t = df.groupby(["system", dim]).apply(lambda g: g.cp_errors.sum() / g.ref_words.sum(), include_groups=False).unstack(dim)
            else:
                t = df.groupby(["system", dim])[metric].mean().unstack(dim)
            t = t.reindex(order)[levels].map(pct)
            md += [f"### {name} by {dim.replace('_', ' ')}\n", t.to_markdown(), ""]
    t = df.groupby(["system", "n_speakers"]).der.mean().unstack().reindex(order).map(pct)
    md += ["### DER by number of speakers\n", t.to_markdown(), ""]

    # paired comparisons
    piv_cp = df.assign(r=df.cp_errors / df.ref_words).pivot(index="id", columns="system", values="r")
    piv_der = df.pivot(index="id", columns="system", values="der")
    comps = [("A-spectral", "B-spectral", "Order A − Order B (proposal's order vs ours)"),
             ("B-nosep", "B-spectral", "no separation − targeted separation"),
             ("B-gmm", "B-spectral", "GMM − spectral clustering"),
             ("B-pyannote", "B-spectral", "pyannote 3.1 − our diarizer"),
             ("oracle-mix", "oracle-sep", "true timeline: mixture − separated overlaps")]
    prow = []
    for a, b, label in comps:
        m, lo, hi = paired_diff_ci(piv_cp[a], piv_cp[b])
        dm, dlo, dhi = paired_diff_ci(piv_der[a], piv_der[b])
        prow.append({"comparison": label, "Δ cpWER (points)": f"{100 * m:+.1f} [{100 * lo:+.1f}, {100 * hi:+.1f}]",
                     "Δ DER (points)": f"{100 * dm:+.1f} [{100 * dlo:+.1f}, {100 * dhi:+.1f}]",
                     "conversations where first is worse (cpWER)": f"{int((piv_cp[a] > piv_cp[b]).sum())}/{len(piv_cp)}"})
    md += [f"## Paired comparisons (same {n_conv} conversations; mean difference with 95 % bootstrap CI — "
           "positive = the first system has MORE errors)\n", pd.DataFrame(prow).to_markdown(index=False), ""]
    OUT_MD.write_text("\n".join(md), encoding="utf-8")

    # ------------------------------------------------------------ figures
    # 1) Order A vs Order B by overlap level (cpWER and DER side by side — two panels, one axis each)
    fig, axes = plt.subplots(1, 2, figsize=(10, 3.4))
    systems = ["B-spectral", "A-spectral", "B-pyannote"]
    labels = ["Order B (ours: diarize → separate overlaps)", "Order A (proposal: separate everything first)",
              "Order B with pyannote 3.1 diarization (reference)"]
    for ax, metric, title in ((axes[0], "cpwer", "Who-said-what error (cpWER)"), (axes[1], "der", "Who-spoke-when error (DER)")):
        vals, errs = {}, {}
        for s in systems:
            vals[s], errs[s] = {}, {}
            for lvl in OVL:
                g = df[(df.system == s) & (df.overlap_level == lvl)]
                if metric == "cpwer":
                    v = g.cp_errors.sum() / g.ref_words.sum()
                    ci = boot_ci((g.cp_errors / g.ref_words).to_numpy(), g.ref_words.to_numpy())
                else:
                    v = g.der.mean()
                    ci = boot_ci(g.der.to_numpy())
                vals[s][lvl], errs[s][lvl] = v, np.abs(np.array(ci) - v)
        bar_group(ax, OVL, systems, vals, errs, [BLUE, ORANGE, GREY], labels, "error rate (lower is better)")
        ax.set_title(title, loc="left")
    handles, labs = axes[0].get_legend_handles_labels()
    fig.legend(handles, labs, loc="upper center", ncol=3, bbox_to_anchor=(0.5, 1.08), fontsize=9)
    fig.tight_layout()
    fig.savefig(FIG / "order_A_vs_B.png", bbox_inches="tight")
    plt.close(fig)

    # 2) Error cascade: where do the transcript errors come from?
    steps = [("oracle-clean", "ASR alone\n(clean voice,\ntrue timeline)"), ("oracle-mix", "+ noise &\noverlap"),
             ("oracle-sep", "+ separate\noverlaps"), ("B-spectral", "+ our\ndiarization\n(full system)"),
             ("A-spectral", "proposal's\norder A\n(full system)")]
    vals = [main_t.loc[s, "cpWER"] for s, _ in steps]
    fig, ax = plt.subplots(figsize=(7.6, 3.4))
    cols = [GREY, GREY, GREY, BLUE, ORANGE]
    ax.bar(range(len(steps)), vals, 0.6, color=cols)
    for i, v in enumerate(vals):
        ax.text(i, v + 0.008, pct(v), ha="center", va="bottom", color=INK, fontsize=9)
    ax.set_xticks(range(len(steps)), [l for _, l in steps], fontsize=8.5)
    ax.yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(lambda y, _: f"{100 * y:.0f}%"))
    ax.set_ylabel("cpWER (lower is better)")
    ax.set_title("How errors build up through the pipeline (test set)", loc="left")
    ax.grid(axis="x", visible=False)
    fig.tight_layout()
    fig.savefig(FIG / "error_cascade.png", bbox_inches="tight")
    plt.close(fig)

    # 3) Clustering: spectral vs GMM vs pyannote, by number of speakers
    fig, ax = plt.subplots(figsize=(6.2, 3.2))
    systems = ["B-spectral", "B-gmm", "B-pyannote"]
    vals = {s: df[df.system == s].groupby("n_speakers").der.mean().to_dict() for s in systems}
    errs = {s: {k: np.abs(np.array(boot_ci(df[(df.system == s) & (df.n_speakers == k)].der.to_numpy())) - vals[s][k])
                for k in vals[s]} for s in systems}
    groups = sorted(vals["B-spectral"])
    k = len(systems)
    x = np.arange(len(groups))
    for i, (s, col, lab) in enumerate(zip(systems, [BLUE, ORANGE, GREY],
                                          ["spectral clustering (ours)", "GMM (ours)", "pyannote 3.1 (reference)"])):
        ax.bar(x + (i - 1) * 0.27, [vals[s][g] for g in groups], 0.25, color=col, label=lab,
               yerr=np.array([errs[s][g] for g in groups]).T, error_kw={"elinewidth": 1, "ecolor": INK2, "capsize": 2})
    ax.set_xticks(x, [f"{g} speakers" for g in groups])
    ax.yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(lambda y, _: f"{100 * y:.0f}%"))
    ax.set_ylabel("DER (lower is better)")
    ax.set_title("Stage 2 · clustering methods", loc="left")
    ax.legend(loc="upper left", fontsize=8.5)
    ax.grid(axis="x", visible=False)
    fig.tight_layout()
    fig.savefig(FIG / "stage2_clustering.png", bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {OUT_MD} and figures in {FIG}")


if __name__ == "__main__":
    main(*(sys.argv[1:2] or []))
